### ISSUE TITLE
Add option to configure `cargo doc` arguments

### ISSUE THREAD

**Issue by srid** [srid/cargo-doc-live#2]
https://github.com/srid/cargo-doc-live/blob/fb1d4439d847f01ce4ccf1905d1630c1994569b0/flake-module.nix#L57

Instead of hardcoding `--document-private-items --all-features`, allow the user to specify them as module options. Eg.:

```nix
{
  cargo-doc-live = {
    cargo-doc-args = "--document-private-items --all-features";
  };
}
```

**Comment by srid** [comment]
To implement this, simply look at how we defined the `crateName` option:

https://github.com/srid/cargo-doc-live/blob/fb1d4439d847f01ce4ccf1905d1630c1994569b0/flake-module.nix#L21-L27

**Comment by srid** [comment]
Looks like we can avoid this option entirely by adding this to `Cargo.toml`?

```toml
[package.metadata.docs.rs]
all-features = true
cargo-args = ["--document-private-items"]
```

https://docs.rs/about/metadata
